name: ci

on:
  pull_request:
  push:
    branches: [main]

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
      - name: Install
        run: uv sync --all-extras --frozen
      - name: Lint
        run: make lint
      - name: Test
        run: make test
